// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Carros.Model
{
    public partial class Carros
    {

        public int IdCarro { get; set; }
        public string ModeloCarro { get; set; }
        public int Preco { get; set; }


    }
}