// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Carros.Model
{
    public partial class Concessionarias
    {
        public int IdConcessionaria { get; set; }
        public string NomeConcessionaria { get; set; }
        public string Gerente { get; set; }
        public string Cidade { get; set; }
    }
}