// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Carros.Model
{
    public partial class Contas
    {
        public string Usuario { get; set; }
        public string Senha { get; set; }
        public int IdUsuario { get; set; }

        public virtual Funcionarios IdUsuarioNavigation { get; set; }
    }
}