// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Carros.Model
{
    public partial class Funcionarios
    {

        public int IdFuncionario { get; set; }
        public int IdConcessionaria { get; set; }
        public string NomeFuncionario { get; set; }
        public string Cpf { get; set; }
        public string Cargo { get; set; }
    }
}