// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Carros.Model
{
    public partial class Vendas
    {
        public int IdVenda { get; set; }
        public int IdFuncionario { get; set; }
        public int IdCliente { get; set; }
        public int IdCarro { get; set; }
        public int IdConcessionaria { get; set; }
    }
}